name: CI/CD Pipeline
run-name: ${{ github.actor }} is  testing out GitHub Actions
on:
  push:
    branches:
      - master
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Analyze code with Checkstyle
        run: ./gradlew check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: practice5-jar
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Gather package as JAR
        run: gradle jar
#      - name: Download build artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: jar-file
#          path: build/libs/
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t practice5:latest .
        working-directory: ${{ github.workspace }}
      - name: Push Docker image
        run: |
          docker tag practice5:latest ${{ secrets.DOCKER_USERNAME }}/practice5:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/practice5:latest
#      - name: Build and push Docker image
#        run: |
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/practice5:latest .
#          docker push ${{ secrets.DOCKER_USERNAME }}/practice5:latest